### ISSUE TITLE
JavaScript linking problem 

### ISSUE THREAD

**Issue by saahiyo** [saahiyo/DOM_addFriends#1]
Getting problem in JavaScript , that gives issue in button

**Comment by tchisama** [comment]
i fixed it for you the problem was that u put the script tag `<script>` in the top and u didnt let the document to load , u can fix it by puting the `<script>` tag as the last element in the body

**Comment by saahiyo** [comment]
Okay got it , thanks for the help.

**Comment by saahiyo** [comment]
Fixed issues
